# Shared packages available on archlinux, debian void.
shared_pkgs: &shared_pkgs
  - ansible
  - curl
  - docker
  - docker-compose
  - git
  - htop
  - jq
  - man-db
  - rsync
  - tmux
  - vim
  - wget
  - zsh

# Shared packages available on archlinux and void only.
shared_arch_void_pkgs: &shared_arch_void_pkgs
  - base-devel
  - cronie
  - go
  - inetutils
  - neovim
  - nodejs
  - openssh
  - ruby
  - shellcheck
  - yarn

# python+python2
python_pkgs: &python_pkgs
  - python
  - python-pip
  - python2
  - python2-pip

# python3+python
python3_pkgs: &python3_pkgs
  - python3
  - python3-pip
  - python
  - python-pip

archlinux_pkgs:
  - *shared_pkgs
  - *shared_arch_void_pkgs
  - *python_pkgs
  - gnu-netcat
  - gnupg
  - npm
  - pkgfile
  - rubygems

debian_pkgs:
  - *shared_pkgs
  - *python3_pkgs
  - build-essential
  - cron
  - gnupg
  - inetutils-tools
  - netcat-openbsd
  - openssh-client

void_pkgs:
  - *shared_pkgs
  - *shared_arch_void_pkgs
  - *python3_pkgs
  - gnupg2
  - netcat
